development: &development
  adapter: postgresql
  database: ivision_development
  pool: 5
  host:     localhost
  encoding: unicode
  timeout: 5000
  username: postgres
  password: postgres
test:
  <<: *development
  database: ivision_test

production: &production
  adapter: postgresql
  database: ivision_production
  pool:     5
  username: postgres
  password: postgres
staging:
  <<: *production